-- AlterTable
ALTER TABLE "public"."sinh_vien" ADD COLUMN     "avatar_url" TEXT,
ADD COLUMN     "dia_chi_gia_dinh" TEXT,
ADD COLUMN     "diem_thpt" DECIMAL(4,2),
ADD COLUMN     "email_phu" VARCHAR(100),
ADD COLUMN     "ky_nang" TEXT,
ADD COLUMN     "muc_tieu" TEXT,
ADD COLUMN     "mui_gio" VARCHAR(50) DEFAULT 'Asia/Ho_Chi_Minh',
ADD COLUMN     "nam_tot_nghiep_thpt" INTEGER,
ADD COLUMN     "ngay_cap_nhat" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "ngon_ngu" VARCHAR(5) DEFAULT 'vi',
ADD COLUMN     "sdt_cha" VARCHAR(15),
ADD COLUMN     "sdt_khan_cap" VARCHAR(15),
ADD COLUMN     "sdt_me" VARCHAR(15),
ADD COLUMN     "so_thich" TEXT,
ADD COLUMN     "ten_cha" VARCHAR(100),
ADD COLUMN     "ten_me" VARCHAR(100),
ADD COLUMN     "thong_bao_email" BOOLEAN DEFAULT true,
ADD COLUMN     "thong_bao_sdt" BOOLEAN DEFAULT false,
ADD COLUMN     "truong_thpt" VARCHAR(200);
